### ISSUE TITLE
Unable to login using user test accounts, throws error

### ISSUE THREAD

**Issue by ronakf11** [gcivil-nyu-org/match-a-pet#122] opened 2020-11-24 23:16 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Throws following error when i try to log in with test account
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
File "/app/accounts/signals.py", line 24, in save_profile
    instance.uprofile.save()
  File "/app/accounts/models.py", line 60, in save
    img = Image.open(self.user_profile_image.path)
  File "/app/.heroku/python/lib/python3.6/site-packages/PIL/Image.py", line 2891, in open
    fp = builtins.open(filename, "rb")

Exception Type: FileNotFoundError at /login/
Exception Value: [Errno 2] No such file or directory: '/app/media/user_profile_pics/obby-rh-OlnRizv2Yb4-unsplash.jpg'
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

## Steps to Reproduce

1.
2.
3.
4.

**Comment by benji7890** [comment] 2020-11-29 01:01
duplicate of major issue

**Closed as completed by benji7890** 2020-11-29 01:01 UTC
